name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.102
      - name: Dotnet Publish
        run: |
          dotnet publish -c Release -o deploy 
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: /home/runner/work/blog/blog
          remote: ${{ secrets.REMOTE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: dotnet run
          remote: ${{ secrets.REMOTE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}